import { test } from '@playwright/test'
import nodemailer from 'nodemailer'
import * as auth from '../login.json'

const url = "https://www.amazon.com/s?k=kitchen+and+dining&crid=1CR304DY9B6JB&sprefix=%2Caps%2C327&ref=nb_sb_ss_recent_1_0_recent"

test("Amazon price drop notification", async ({ page }) => {
    await page.goto(url)
    await page.waitForLoadState('load')
    await page.waitForSelector('.a-price-whole')
    const prices = page.locator('.a-price-whole')
    
    let totalPrice: number = 0

    await Promise.all(
        (await prices.all()).map(async ele => {
            const priceText = await ele.innerText()
            const priceValue = Number(priceText.replace(/,/g, ''))
            if (!isNaN(priceValue)) {
                totalPrice += priceValue
            }
        })
    )
    console.log(totalPrice + "VND")

    // FIX 1: Add 'await' here so the test waits for the email to finish
    await sendEmailNotification(totalPrice, await prices.count())
})

// FIX 2: Change this function to return a Promise
async function sendEmailNotification(totalPrice: number, totalItems: number) {
    console.log("Preparing to send professional email report...");

    // 1. Calculate Average Price for better insights
    const averagePrice = totalItems > 0 ? (totalPrice / totalItems).toFixed(2) : "0";
    const timestamp = new Date().toLocaleString();

    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: auth.email,
            pass: auth.password
        }
    });

    // 2. Professional HTML Template
    const emailHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
        
        <div style="background-color: #232f3e; padding: 20px; text-align: center;">
            <h2 style="color: #ffffff; margin: 0;">Amazon Price Tracker</h2>
            <p style="color: #dddddd; margin: 5px 0 0; font-size: 14px;">Kitchen & Dining Report</p>
        </div>

        <div style="padding: 30px; background-color: #fcfcfc;">
            <p style="font-size: 16px; color: #333;">Here is the summary of your latest scraping run on <b>${timestamp}</b>:</p>
            
            <div style="display: flex; margin-bottom: 25px; border-bottom: 2px solid #eee; padding-bottom: 20px;">
                <div style="flex: 1; text-align: center; border-right: 1px solid #eee;">
                    <div style="font-size: 12px; color: #777; text-transform: uppercase;">Total Items</div>
                    <div style="font-size: 24px; font-weight: bold; color: #232f3e;">${totalItems}</div>
                </div>
                <div style="flex: 1; text-align: center; border-right: 1px solid #eee;">
                    <div style="font-size: 12px; color: #777; text-transform: uppercase;">Total Value</div>
                    <div style="font-size: 24px; font-weight: bold; color: #b12704;">${totalPrice.toLocaleString()} <span style="font-size:14px">VND</span></div>
                </div>
                 <div style="flex: 1; text-align: center;">
                    <div style="font-size: 12px; color: #777; text-transform: uppercase;">Avg Price</div>
                    <div style="font-size: 24px; font-weight: bold; color: #232f3e;">${averagePrice}</div>
                </div>
            </div>

            <div style="text-align: center; margin-top: 30px;">
                <a href="${url}" style="background-color: #f0c14b; border: 1px solid #a88734; color: #111; padding: 12px 25px; text-decoration: none; border-radius: 3px; font-weight: bold; font-size: 16px; display: inline-block;">
                    View Products on Amazon
                </a>
            </div>
        </div>

        <div style="background-color: #f3f3f3; padding: 15px; text-align: center; font-size: 12px; color: #888;">
            Generated by Playwright Automation • <a href="#" style="color: #666;">Unsubscribe</a>
        </div>
    </div>
    `;

    return new Promise<void>((resolve, reject) => {
        transporter.sendMail({
            from: `Playwright Bot <${auth.email}>`, // Adds a friendly sender name
            to: 'helenjacqueline03us@gmail.com',
            subject: `📊 Amazon Report: ${totalItems} Items Found | Total ${totalPrice} VND`,
            text: `Report generated on ${timestamp}. Found ${totalItems} items. Total: ${totalPrice} VND. Link: ${url}`, // Fallback text
            html: emailHtml
        }, (err, info) => {
            if (err) {
                console.log("❌ Error sending email: " + err.message);
                reject(err);
            } else {
                console.log("✅ Email sent successfully: " + info.response);
                resolve();
            }
        });
    });
}